### ISSUE TITLE
Roadmap to 1.2.0

### ISSUE THREAD

**Issue by wapmorgan** [wapmorgan/UnifiedArchive#25]
- [x] Ability to set/clear passwords and open archives with passwords
- [x] Ability to add files from string
- [x] Ability to iterate over files list
